# Generated by Django 5.0.6 on 2024-07-22 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0003_booking_created_at_booking_updated_at_booking_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='players',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
