# Generated by Django 5.0.6 on 2024-07-23 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0004_alter_gameroom_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favourite',
            field=models.TextField(blank=True, default='Football', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.TextField(blank=True, default='Kerala', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pref_position',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='/dummy/empty.png', upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='players',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
