# Generated by Django 5.0.6 on 2024-07-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
