# Generated by Django 5.0.6 on 2024-07-25 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0007_notification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='group_admin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='group_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
