# Generated by Django 5.0.6 on 2024-07-30 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0009_rename_created_at_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playeranalysis',
            old_name='dble',
            new_name='defence',
        ),
        migrations.RenameField(
            model_name='playeranalysis',
            old_name='defc',
            new_name='dribble',
        ),
        migrations.RenameField(
            model_name='playeranalysis',
            old_name='pas',
            new_name='games_played',
        ),
        migrations.RenameField(
            model_name='playeranalysis',
            old_name='total_play',
            new_name='pass_acuracy',
        ),
    ]
