# Generated by Django 5.0.6 on 2024-07-30 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0010_rename_dble_playeranalysis_defence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='pref_position',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='visibility',
        ),
        migrations.RemoveField(
            model_name='turf',
            name='is_open',
        ),
        migrations.AddField(
            model_name='playeranalysis',
            name='pref_position',
            field=models.TextField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='head',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_class',
            field=models.CharField(choices=[('group', 'group'), ('payment', 'payment'), ('booking', 'booking')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfapp.booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
