# Generated by Django 5.0.6 on 2024-07-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0011_remove_customuser_favourite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
