# Generated by Django 5.0.6 on 2024-08-04 05:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0015_remove_slot_booked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='turfapp.slot'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('turf', 'time_slot', 'date')},
        ),
    ]
