# Generated by Django 5.0.6 on 2024-08-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0017_alter_notification_notification_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='usd', max_length=3),
        ),
    ]
