# Generated by Django 5.0.6 on 2024-08-13 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0019_alter_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='turf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turfapp.turf'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refund', 'Refund')], default='Pending', max_length=50),
        ),
    ]
