# Generated by Django 5.0.6 on 2024-08-13 07:29

import turfapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0020_alter_booking_turf_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(blank=True, default=turfapp.models.get_current_date, null=True),
        ),
    ]
