# Generated by Django 5.0.6 on 2024-08-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0021_alter_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='image',
            field=models.ImageField(default='/dummy/turf-default.jpg', upload_to='turf_images/'),
        ),
    ]
