# Generated by Django 5.0.6 on 2024-08-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0022_turf_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
