# Generated by Django 5.0.6 on 2024-08-24 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0023_turf_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='time_slot',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='turfapp.slot'),
        ),
    ]
