# Generated by Django 5.0.6 on 2024-08-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0024_alter_gameroom_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
    ]
