# Generated by Django 5.0.6 on 2024-08-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0025_gameroom_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeranalysis',
            name='games_played',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
