# Generated by Django 5.0.6 on 2024-08-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0026_alter_playeranalysis_games_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeranalysis',
            name='diving',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playeranalysis',
            name='positioning',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playeranalysis',
            name='reflexes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
