# Generated by Django 5.0.6 on 2024-08-29 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0028_alter_playeranalysis_defence_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turfreview',
            options={'ordering': ['-created_at']},
        ),
    ]
