# Generated by Django 5.0.6 on 2024-08-29 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0029_alter_turfreview_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-created_at']},
        ),
    ]
