# Generated by Django 5.0.6 on 2024-08-30 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0031_alter_gameroom_group_admin_alter_gameroom_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='time_slot',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='turfapp.slot'),
        ),
    ]
